chip_out:
    /DATA/usr/c.leemans/projects/chip_snake

experiment:
    K562:
        Struhl2011:
            NELFE:
                ENCSR000DOF:
                    [SRR502172, SRR502173]
        Snyder2016:
            POL2:
                ENCSR388QZF:
                    [SRR5111542, SRR5111543]
                ENCSR031TFS:
                    [SRR5112448, SRR5112449]
        Snyder2012:
            POL2AS2:
                ENCSR000EGF:
                    [SRR502194, SRR502195]
            MYC:
                ENCSR000EGJ:
                    [SRR502421, SRR502422]
        Liu2018:
            H3K9me2:
                ab1220:
                    [SRR5287112, SRR5287113]
            H3K9me3:
                ab1220:
                    [SRR5287116, SRR5287117]
                ab8898:
                    [SRR5287100, SRR5287101]
    # Salzberg2017:
    #     H3K9me2:
    #         GSM1846169:
    #             [SRR2148301, SRR3503803, SRR3503783]
    #         UNC0638:
    #             [SRR2148302, SRR3503784]
    #     H3K9me3:
    #         GSM1846192:
    #             [SRR2148320]
    #     H3.C-tail:
    #         GSM1846180:
    #             [SRR2148312]
        Stamatoyannopoulos2011:
            H3K36me3:
                ENCSR000DWB:
                    [SRR577540, SRR577541]
        Schmidl2015:
            H3K27ME3:
                chipmentation:
                    [SRR2085903, SRR2085904]
                chipseq:
                    [SRR2085893, SRR2085894]
        Ratnakumar2012:
            macroH2A:
                GSE35339:
                    [SRR402382]
        Fu2013:
            H3K79me2:
                GSM865283:
                    [SRR401813]
        Bernstein2012:
            EZH2:
                ENCSR000AQE:
                    [SRR568431, SRR568432]
            H3K79me2:
                ENCSR000APD:
                    [SRR227378, SRR227379]
            H4K20me1:
                ENCSR000AKX:
                    [SRR227427, SRR227428]
            H3K9me3:
                ENCSR000APE:
                    [SRR227643, SRR227644]

control:
    K562:
        Struhl2011:
            NELFE:
                ENCSR000DOF:
                    [SRR502109, SRR502110]
        Snyder2016:
            POL2:
                ENCSR388QZF:
                    [SRR5111209, SRR5111210]
                ENCSR031TFS:
                    [SRR5111209, SRR5111210]
        Snyder2012:
            POL2AS2:
                ENCSR000EGF:
                    [SRR502641]
            MYC:
                ENCSR000EGJ:
                    [SRR502641]
        Liu2018:
            H3K9me2:
                ab1220:
                    [SRR5287120, SRR5287121]
            H3K9me3:
                ab1220:
                    [SRR5287120, SRR5287121]
                ab8898:
                    [SRR5287106, SRR5287107]
        # Salzberg2017:
        #     H3K9me2:
        #         GSM1846169:
        #             [SRR2148307, SRR3503802]
        #         UNC0638:
        #             [SRR2148313]
        #     H3K9me3:
        #         GSM1846192:
        #             [SRR2148307, SRR3503802]
        #     H3.C-tail:
        #         GSM1846180:
        #             [SRR2148307, SRR3503802]
        Stamatoyannopoulos2011:
            H3K36me3:
                ENCSR000DWB:
                    [SRR577521]
        Schmidl2015:
            H3K27ME3:
                chipmentation:
                    [SRR2085912, SRR2085913, SRR2085914]
                chipseq:
                    [SRR2085897, SRR2085898]
        Ratnakumar2012:
            macroH2A:
                GSE35339:
                    [SRR402383]
        Fu2013:
            H3K79me2:
                GSM865283:
                    [SRR401814]
        Bernstein2012:
            EZH2:
                ENCSR000AQE:
                    [SRR227650, SRR5331211, SRR5331212, SRR5331213]
            H3K79me2:
                ENCSR000APD:
                    [SRR227650, SRR5331211, SRR5331212, SRR5331213]
            H4K20me1:
                ENCSR000AKX:
                    [SRR227650, SRR5331211, SRR5331212, SRR5331213]
            H3K9me3:
                ENCSR000APE:
                    [SRR227650, SRR5331211, SRR5331212, SRR5331213]



is_paired:
    K562:
        Struhl2011:
            NELFE:
                ENCSR000DOF: False
        Snyder2016:
            POL2:
                ENCSR388QZF: True
                ENCSR031TFS: True
        Snyder2012:
            POL2AS2:
                ENCSR000EGF: False
            MYC:
                ENCSR000EGJ: False
        Liu2018:
            H3K9me2:
                ab1220: True
            H3K9me3:
                ab1220: True
                ab8898: True

        Salzberg2017:
            H3K9me2:
                GSM1846169: False
                UNC0638: False
            H3K9me3:
                GSM1846192: False
            H3.C-tail:
                GSM1846180: False
        Stamatoyannopoulos2011:
            H3K36me3:
                ENCSR000DWB: False
        Schmidl2015:
            H3K27ME3:
                chipmentation: False
                chipseq: False
        Ratnakumar2012:
            macroH2A:
                GSE35339: False
        Fu2013:
            H3K79me2:
                GSM865283: False
        Bernstein2012:
            EZH2:
                ENCSR000AQE: False
            H3K79me2:
                ENCSR000APD: False
            H4K20me1:
                ENCSR000AKX: False
            H3K9me3:
                ENCSR000APE: False




blacklist:
    /DATA/usr/c.leemans/data/tracks/hg19/hg19_blacklist_ENCFF055QTV.bed.gz


replicate_cor_method:
    'pearson'

min_mapq:
    30

bowtie_index:
    '/DATA/data/bowtie2/hg19_1-22_XYM'
