outdir:
    '/DATA/usr/c.leemans/projects/chip_ruben/pipeline_20181008'

bed_summary:
    20180918.RSTP2:
        '/DATA/usr/r.schep/projects/CRISPR_TRIP/20180918_TRIP_5106/indels/data/processed/rs20181007_Mapping_RSTP2_2000_broad_indels.bed'

bed_nearest_domains:
    20180918.RSTP2:
        '/DATA/usr/r.schep/projects/CRISPR_TRIP/20180918_TRIP_5106/indels/data/processed/rs20181007_Mapping_RSTP2_2000_broad_indels.bed'


genome: hg38

celltype: 'K562'

chip_dir:
    '/DATA/usr/c.leemans/projects/chip_snake/'

chip_align_config:
    '/DATA/usr/c.leemans/projects/chip_snake/config.yaml'
chip_align:
    '/DATA/usr/c.leemans/projects/chip_snake/chip_align.snakemake'


use_encode_tracks: False
encode_dir:  /DATA/usr/c.leemans/data/ChIP/bigwig/histone_and_remodelers/tracks
